### ISSUE TITLE
SolidityX Optimizer does not function properly on Linux

### ISSUE THREAD

**Issue by Juuddi** [dominant-strategies/SolidityX#3]
## Description

SolidityX contracts when tested against traditional Solidity contracts require significantly more gas to deploy. Upon first glance, this seems to be an issue with the SolidityX optimizer used during contract compilation.

## Environment

- Hardhat
- Linux (Ubuntu)

## Steps to Reproduce

Using the `Lock.sol` contract provided by the initial hardhat installation.

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.9;

// Uncomment this line to use console.log
// import "hardhat/console.sol";

contract Lock {
    uint public unlockTime;
    address payable public owner;

    event Withdrawal(uint amount, uint when);

    constructor(uint _unlockTime) payable {
        require(
            block.timestamp < _unlockTime,
            "Unlock time should be in the future"
        );

        unlockTime = _unlockTime;
        owner = payable(msg.sender);
    }

    function withdraw() public {
        // Uncomment this line, and the import of "hardhat/console.sol", to print a log in your terminal
        // console.log("Unlock time is %o and block timestamp is %o", unlockTime, block.timestamp);

        require(block.timestamp >= unlockTime, "You can't withdraw yet");
        require(msg.sender == owner, "You aren't the owner");

        emit Withdrawal(address(this).balance, block.timestamp);

        owner.transfer(address(this).balance);
    }
}
```

The test comprised of compiling the `Lock.sol` contract with both SolidityX and Solidity, and then deploying them to one Quai Network chain. The `cumulativeGasUsed` results for the different compilers are as follows:

**Solidity v0.8.9** - 230042 gas used
```json
"cumulativeGasUsed": {
        "type": "BigNumber",
        "hex": "0x03829a"
    },
```

**SolidityX** - 500000 gas used
```json
"cumulativeGasUsed": {
        "type": "BigNumber",
        "hex": "0x4c4b40"
    },
```

As seen above, the Solidity 0.8.9 compiler is significantly more gas efficient during deploys, whereas SolidityX uses the entire gas limit of the block to deploy this very simple contract. This makes deploying larger more complex contracts infeasible.

**Comment by jdowning100** [comment]
This has been fixed.
